name: recipedia
version: '3.3'

volumes:
  recipedia_pg_data:
  recipedia_static:
  recipedia_media:

services:
  db:
    image: postgres:13.0-alpine
    container_name: recipedia_db
    env_file: .env
    volumes:
      - recipedia_pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    container_name: recipedia_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - recipedia_static:/static_backend
      - recipedia_media:/app/media

  frontend:
    container_name: recipedia_frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: recipedia_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - recipedia_static:/etc/nginx/html/static/
      - recipedia_media:/etc/nginx/html/media/

